networks:
  default:
    name: app-network
    driver: bridge

services:
  front-end:
    container_name: front-end
    build:
      context: ./frontend-web/PXLNews
      dockerfile: Dockerfile
    ports:
      - "4200:80"

  config-service:
    container_name: config-service
    build:
      context: ./backend-java/PXLNews/config-service
      dockerfile: Dockerfile
    ports:
      - "8088:8088"

  discovery-service:
    container_name: discovery-service
    build:
      context: ./backend-java/PXLNews/discovery-service
      dockerfile: Dockerfile
    ports:
      - "8061:8061"
    depends_on:
      - config-service

  gateway-service:
    container_name: gateway-service
    build:
      context: ./backend-java/PXLNews/gateway-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - discovery-service

  notification-service:
    container_name: notification-service
    build:
      context: ./backend-java/PXLNews/notification-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - discovery-service
      - notificationservice-db

  messaging-service:
    container_name: messaging-service
    build:
      context: ./backend-java/PXLNews/messaging-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service

  comment-service:
    container_name: comment-service
    build:
      context: ./backend-java/PXLNews/comment-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service
      - commentservice-db

  post-service:
    container_name: post-service
    build:
      context: ./backend-java/PXLNews/post-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
      - postservice-db

  review-service:
    container_name: review-service
    build:
      context: ./backend-java/PXLNews/review-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - ./backend-java/PXLNews/notification-service/.env
    depends_on:
      - discovery-service
      - reviewservice-db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  postservice-db:
    image: mysql:8.0
    container_name: postservice-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'postservice_db'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'toor'
    volumes:
      - db_data_postservice:/var/lib/mysql

  reviewservice-db:
    image: mysql:8.0
    container_name: reviewservice-db
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: 'reviewservice_db'
      MYSQL_ROOT_PASSWORD: 'toor'
    volumes:
      - db_data_reviewservice:/var/lib/mysql

  commentservice-db:
    image: mysql:8.0
    container_name: commentservice-db
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: 'commentservice_db'
      MYSQL_ROOT_PASSWORD: 'toor'
    volumes:
      - db_data_commentservice:/var/lib/mysql

  notificationservice-db:
    image: mysql:8.0
    container_name: notificationservice-db
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: 'notificationservice_db'
      MYSQL_ROOT_PASSWORD: 'toor'
    volumes:
      - db_data_notificationservice:/var/lib/mysql

volumes:
  db_data_postservice:
  db_data_reviewservice:
  db_data_commentservice:
  db_data_notificationservice:

