server:
  port: 8085

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "localhost"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
          filters:
            - RewritePath=/employee/(?<path>.*), /$\{path}
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**
          filters:
            - RewritePath=/department/(?<path>.*), /$\{path}
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
          filters:
            - RewritePath=/notification/(?<path>.*), /$\{path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
